"""add username + password_hash, make feishu nullable

Revision ID: 1fb8e6db0705
Revises: b43fd8e304c4
Create Date: 2026-06-17 16:08:56.139706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fb8e6db0705'
down_revision: Union[str, None] = 'b43fd8e304c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=False))
    op.alter_column('users', 'feishu_open_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'feishu_open_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
