"""initial patient and doctor schema

Revision ID: c50689378714
Revises:
Create Date: 2026-07-13 13:30:06.908474
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c50689378714'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietary_habit_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('email_verify_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verify_codes_email'), 'email_verify_codes', ['email'], unique=False)
    op.create_table('invitation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('patient','doctor','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=80), nullable=False),
    sa.Column('institution', sa.String(length=160), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('medical_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_medical_images_sha256'), 'medical_images', ['sha256'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('residence', sa.String(length=200), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("sex IN ('male','female')", name='ck_patient_profiles_sex'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_patient_profiles_email'), 'patient_profiles', ['email'], unique=True)
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('grade_index', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('is_borderline', sa.Boolean(), nullable=False),
    sa.Column('secondary_grade', sa.String(length=20), nullable=True),
    sa.Column('secondary_confidence', sa.Float(), nullable=True),
    sa.Column('medical', sa.JSON(), nullable=False),
    sa.Column('lifestyle', sa.JSON(), nullable=False),
    sa.Column('report_html', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['medical_images.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_grade_created', 'analysis_records', ['grade_index', 'created_at'], unique=False)
    op.create_index('ix_analysis_patient_created', 'analysis_records', ['patient_profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_records_patient_profile_id'), 'analysis_records', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_performed_by_user_id'), 'analysis_records', ['performed_by_user_id'], unique=False)
    op.create_table('doctor_patient_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('authorization_method', sa.String(length=40), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'patient_profile_id', name='uq_doctor_patient_link')
    )
    op.create_index(op.f('ix_doctor_patient_links_doctor_id'), 'doctor_patient_links', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_links_patient_profile_id'), 'doctor_patient_links', ['patient_profile_id'], unique=False)
    op.create_table('patient_dietary_habits',
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('dietary_habit_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dietary_habit_option_id'], ['dietary_habit_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_profile_id', 'dietary_habit_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_dietary_habits')
    op.drop_index(op.f('ix_doctor_patient_links_patient_profile_id'), table_name='doctor_patient_links')
    op.drop_index(op.f('ix_doctor_patient_links_doctor_id'), table_name='doctor_patient_links')
    op.drop_table('doctor_patient_links')
    op.drop_index(op.f('ix_analysis_records_performed_by_user_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_patient_profile_id'), table_name='analysis_records')
    op.drop_index('ix_analysis_patient_created', table_name='analysis_records')
    op.drop_index('ix_analysis_grade_created', table_name='analysis_records')
    op.drop_table('analysis_records')
    op.drop_index(op.f('ix_patient_profiles_email'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_medical_images_sha256'), table_name='medical_images')
    op.drop_table('medical_images')
    op.drop_table('doctor_profiles')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('invitation_codes')
    op.drop_index(op.f('ix_email_verify_codes_email'), table_name='email_verify_codes')
    op.drop_table('email_verify_codes')
    op.drop_table('dietary_habit_options')
    # ### end Alembic commands ###
